# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import service_pb2 as service__pb2


class PredictStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.PredictPerformance = channel.unary_unary(
        '/proto.Predict/PredictPerformance',
        request_serializer=service__pb2.PredictRequest.SerializeToString,
        response_deserializer=service__pb2.PredictReply.FromString,
        )
    self.getModel = channel.unary_unary(
        '/proto.Predict/getModel',
        request_serializer=service__pb2.ModelRequest.SerializeToString,
        response_deserializer=service__pb2.ModelReply.FromString,
        )
    self.trainModel = channel.unary_unary(
        '/proto.Predict/trainModel',
        request_serializer=service__pb2.TrainRequest.SerializeToString,
        response_deserializer=service__pb2.TrainReply.FromString,
        )


class PredictServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def PredictPerformance(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getModel(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def trainModel(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PredictServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'PredictPerformance': grpc.unary_unary_rpc_method_handler(
          servicer.PredictPerformance,
          request_deserializer=service__pb2.PredictRequest.FromString,
          response_serializer=service__pb2.PredictReply.SerializeToString,
      ),
      'getModel': grpc.unary_unary_rpc_method_handler(
          servicer.getModel,
          request_deserializer=service__pb2.ModelRequest.FromString,
          response_serializer=service__pb2.ModelReply.SerializeToString,
      ),
      'trainModel': grpc.unary_unary_rpc_method_handler(
          servicer.trainModel,
          request_deserializer=service__pb2.TrainRequest.FromString,
          response_serializer=service__pb2.TrainReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'proto.Predict', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
